name: skScraft
author: Scraft Official
description: Bungee packet based condition and events.
version: 1.3
main: me.scraft.addon.Main
softdepend: [Skript, BungeeBridgeC]
commands:
  skScraft reload:
      description: Reload config file of skScraft addon.
  skScraft:
      description: Print help information fo skScraft addon.
